print("╔═════════════════════╗")
print("║     Sayı Tahmin     ║")
print("║═════════════════════║")
print(" ║")
print("║  ║")
print("║   ║")
print("║              ║")
print("║                     ║")
print("║    Seçimiz nedir?   ║")
print("╚═════════════════════╝")
